[package]
name = "crypto"
version = "1.0.0-pre.3"
edition = "2018"

[dependencies]
ed25519-dalek = "1.0.0-pre.3"
hex = "^0.4"
bincode = "^0.9"
criterion = "0.3"
rand = "0.7"
sha2 = "0.8"
wasm-bindgen = "0.2.63"

[lib]
crate-type = ["cdylib", "rlib"]